name: Build and Release CommandComparator

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload build artifact (non-tag)
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: CommandComparator-jar
          path: build/libs/CommandComparator.jar

      - name: Create GitHub Release (on tag)
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/CommandComparator.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
